version: '3.8'

networks:
   lyso-net:
      driver: bridge
      name: lyso-net

services:
  mysql:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbrow-blog
      - MYSQL_USER=root
    ports: 
      - 3306:3306
    networks:
      - lyso-net
  blog:
    build:
      context: .
      args: 
        - WAR_FILE=/bbrow-blog-0.0.1-SNAPSHOT.war
    networks:
     - lyso-net
    environment: 
      - MYSQL_HOST=mysql
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8888:8080